version: 2

models:
  - name: customers
    description: '{{ doc ("customers")}}'
    columns:
      - name: customer_id
        description: Primary key of the customers table
        tests:
          - unique
          - not_null

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
  - name: orders
    description: '{{ doc ("orders")}}'
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: amount_dollars
        tests:
          - not_null
      - name: status
        description: "{{ doc('order_status') }}"
        tests:
              - accepted_values:
                  values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

      
      